sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  - docker build -t skandyla/mongo .
#  - sudo pip install docker-compose
#  - docker-compose version

#script:
  #- docker-compose up -d
