sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  - docker build -t skandyla/mongo .
  - sudo pip install docker-compose
  - docker-compose version

script:
  - docker-compose up -d
  - docker run --net host -it mongo mongo -u admin -padminpass admin --eval "db.serverStatus()"
  - docker run --net host -it mongo mongo -u admin -padminpass admin --eval "db.adminCommand( { listDatabases: 1 } )"
  - docker-compose down
